export interface Promotion {
  PromotionPageId: number;
  Name: string;
  PromotionStartDateUtc: string;
  PromotionEndDateUtc: string;
  Items: PromotionItem[]
}

export interface PromotionItem {
  ItemId: string;
  CategoryName: string;
  NumberOfPages: number;
  Discount: number;
  IsProductBasedPromotion: boolean;
  FreePages: number;
  Products: number[];
}

export interface PromotionDictionary { [key: string]: { [key: string]: string } };

export interface PromotionName { Name: string, DisplayName: string };
export const PromotionNames: PromotionName[] = [
  { "Name": "MILKA Photo Books", "DisplayName": "MILK Premium Photo Books" },
  { "Name": "MILKA Albums", "DisplayName": "MILK Premium Albums" },
  { "Name": "MILKO Photo Books", "DisplayName": "Classic Photo Books" },
  { "Name": "MILKO Albums", "DisplayName": "MILK Classic Albums" },
  { "Name": "MKT MILKA Medium Photo Books", "DisplayName": "MILK Premium Medium Photo Books" },
  { "Name": "MKT MILKA Large Photo Books", "DisplayName": "MILK Premium Large Photo Books" },
  { "Name": "MKT MILKA Photo Albums", "DisplayName": "MILK Premium Photo Albums" },
  { "Name": "MKT All Photo Books and Albums", "DisplayName": "MILK Photo Books and Albums" },
  { "Name": "MKT Large Formats", "DisplayName": "Large format Photo Books and Albums" },
  { "Name": "MKT MILK A Boxes", "DisplayName": "MILK Premium Presentation Boxes" },
  { "Name": "MKT MILKO MLPB", "DisplayName": "MILK Classic Medium Landscape Photo Book" },
  { "Name": "MKT MILKO LLPB", "DisplayName": "MILK Classic Large Landscape Photo Book" },
  { "Name": "MKT MOLESKINE Medium PB", "DisplayName": "Moleskine Photo Books" },
  { "Name": "MKT MOLESKINE Classics", "DisplayName": "Moleskine Classic Photo Books" },
  { "Name": "MKT MOLESKINE Monograph", "DisplayName": "Moleskine Monograph Photo Book" },
  { "Name": "MKT MILKA LLPB and LPPB", "DisplayName": "MILK Premium Photo Book" },
  { "Name": "MKT MILKA LSPB", "DisplayName": "MILK Premium Large Square Photo Book" },
  { "Name": "MKT MILK A - 160 page Large PB", "DisplayName": "MILK Premium 160 page Large Photo Book" },
  { "Name": "MKT MILKO LLPB - with box", "DisplayName": "MILK Classic Large Landscape Photo Book + Box" },
  { "Name": " missing name? ", "DisplayName": "MILK Premium Large Landscape + Portrait Photo Book + Box" },
  { "Name": "MKT MILKA MPB - Box", "DisplayName": "MILK Premium Medium Photo Book + Pres Box" },
  { "Name": "MKT MILK A MEDIUM LANDSCAPE PH", "DisplayName": "MILK Premium Medium Landscape" },
  { "Name": "MKT All MILK Books and Albums", "DisplayName": "MILK Photo Books + Albums" },
  { "Name": "MKT Books with a Box", "DisplayName": "MILK Photo Book + Pres Box" },
  { "Name": "MKT All Photo Books", "DisplayName": "MILK Photo Books" },
  { "Name": "MKT - ALL MILK O Product", "DisplayName": "MILK Classic Range" },
  { "Name": "MILKA Pres Box", "DisplayName": "Premium Presentation Box" },
  { "Name": "MKT - ALL Photo Albums", "DisplayName": "MILK Photo Album" },
  { "Name": "MILKO Pres Box", "DisplayName": "Classic Presentation Box" },
  { "Name": "MKT - MILKA Albums + Box", "DisplayName": "MKT - MILKA Albums + Box" },
  { "Name": "MKT ALL MILK & Pages", "DisplayName": "MKT ALL MILK & Pages" },
  { "Name": "MKT All Photo Books+Box+UV+Pge", "DisplayName": "All Photo Books + upgrades" },
  { "Name": "MKT Premium Photo Books", "DisplayName": "Premium Photo Books" },
  { "Name": "MKT Premium Photo Albums", "DisplayName": "Premium Photo Albums" },
  { "Name": "MKT Premium Leather Photo Albums", "DisplayName": "Premium Leather Photo Albums" },
  { "Name": "Large Photo Books LP/LL", "DisplayName": "Large Photo Books Portrait and Landscape" },
  { "Name": "MKT Classic Photo Book Set", "DisplayName": "Classic 3 Piece Photo Book Set" },
  { "Name": "MKT Premium Photo Book Set", "DisplayName": "Premium 3 Piece Photo Book Set" },
  { "Name": "MKT Premium Wedding Album Set", "DisplayName": "Premium 3 Piece Wedding Album Set" },
  { "Name": "MKT Classic Family Set", "DisplayName": "Classic 3 Piece Family Set" },
  { "Name": "MKT Premium Family Set", "DisplayName": "Premium 3 Piece Family Set" },
  { "Name": "MKT Classic Wedding Album Set", "DisplayName": "Classic 3 Piece Wedding Album Set" },
  { "Name": "MKT Classic Baby Set", "DisplayName": "Classic 3 Piece Baby Set" },
  { "Name": "MKT MILKA Lrg Albums", "DisplayName": "Large Premium Wedding Album" },
  { "Name": "MKT MILKA Lrg Albums Leather", "DisplayName": "Large Premium Leather Wedding Album" },
  { "Name": "MKT MILKA Med Albums", "DisplayName": "Medium Premium Albums" },
  { "Name": "MKT MILKA Med Albums Leather", "DisplayName": "Medium Premium Leather Albums" },
  { "Name": "MKT MILKA Med Albums Leathers", "DisplayName": "Medium Premium Leather Albums" },
  { "Name": "MKT Soft Cover Photo Books", "DisplayName": "Soft Cover Photo Books" },
  { "Name": "MKT Magazines", "DisplayName": "Wedding Magazines" }
];

export const alreadyTranslated: { [key: string]: { [key: string]: string } } = {
  "de-DE": {
    "MILK Medium Premium Photo Book": "Mittelgroße Premium-Fotobücher",
    "MILK Large Landscape/Portrait Premium Photo Book": "Große Premium-Fotobücher im Querformat/Hochformat",
    "MILK Large Square Premium Photo Book": "Große quadratische Premium-Fotobücher",
    "Premium Photo Books": "Premium-Fotobücher",
    "Classic Photo Albums": "Klassische Fotoalben",
    "Premium Photo Albums": "Premium-Fotoalben",
    "MILK Premium Photo Books": "Premium-Fotobücher",
    "MILK Premium Photo Albums": "Premium-Fotoalben",
    "Large Premium Photo Album": "Große Premium-Fotoalben",
    "MILK Medium Premium Photo Album": "Mittelgroße Premium-Fotoalben",
    "MILK Luxe Softcover Photo Book": "Softcover-Fotobücher",
    "Wedding Magazine": "Hochzeitsmagazine",
    "Medium Landscape Photo Book": "Mittelgroßes Premium-Fotobuch im Querformat",
    "Medium Square Photo Book": "Mittelgroßes quadratisches Premium-Fotobuch",
    "Medium Portrait Photo Book": "Mittelgroßes Premium-Fotobuch im Hochformat",
    "Large Landscape Photo Book": "Großes Premium-Fotobuch im Querformat",
    "Large Square Photo Book": "Großes quadratisches Premium-Fotobuch",
    "Large Portrait Photo Book": "Großes Premium-Fotobuch im Hochformat",
    "Medium Landscape Photo Album": "Mittelgroßes Premium-Fotoalbum im Querformat",
    "Medium Square Photo Album": "Mittelgroßes quadratisches Premium-Fotoalbum",
    "Medium Portrait Photo Album": "Mittelgroßes Premium-Fotoalbum im Hochformat",
    "Large Landscape Photo Album": "Großes Premium-Fotoalbum im Querformat",
    "Large Square Photo Album": "Großes quadratisches Premium-Fotoalbum",
    "Large Portrait Photo Album": "Großes Premium-Fotoalbum im Hochformat",
    "Small Landscape Photo Book - O": "Kleines klassisches Fotobuch im Querformat",
    "Medium Landscape Photo Book - O": "Mittelgroßes klassisches Fotobuch im Querformat",
    "Large Landscape Photo Book - O": "Großes klassisches Fotobuch im Querformat",
    "Medium Landscape Photo Album - O": "Mittelgroßes klassisches Fotoalbum im Querformat",
    "Large Landscape Photo Album - O": "Großes klassisches Fotoalbum im Querformat",
    "MSK Medium Landscape": "Mittelgroßes Moleskine-Fotobuch im Querformat",
    "MSK Medium Square": "Mittelgroßes quadratisches Moleskine-Fotobuch",
    "MSK Landscape Monograph": "Moleskine-Monografie im Querformat",
    "MSK Classic Landscape": "Klassisches Moleskine-Fotobuch im Querformat",
    "MSK Classic Portrait": "Klassisches Moleskine-Format im Hochformat",
    "Medium Square Soft Cover Photo Book": "Mittelgroßes quadratisches Softcover-Fotobuch",
    "Medium Landscape Soft Cover Photo Book": "Mittelgroßes Softcover-Fotobuch im Querformat",
    "Medium Portrait Soft Cover Photo Book": "Mittelgroßes Softcover-Fotobuch im Hochformat",
    "MILK Medium Premium Photo Book with UV Print": "Mittelgroß Premium-Fotobuch mit UV-Druck",
    "MILK Large Landscape/Portrait Premium Photo Book with UV Print": "Großes Premium-Fotobuch im Querformat/Hochformat mit UV-Druck",
    "MILK Large Square Premium Photo Book with UV Print": "Großes quadratisches Premium-Fotobuch mit UV-Druck",
    "Premium Photo Books with UV Print": "Premium-Fotobücher mit UV-Druck",
    "Premium Photo Albums with UV Print": "Premium-Fotoalben mit UV-Druck",
    "MILK Premium Photo Books with UV Print": "Premium-Fotobücher mit UV-Druck",
    "MILK Premium Photo Albums with UV Print": "Premium-Fotoalben mit UV-Druck",
    "Large Premium Photo Album with UV Print": "Großes Premium-Fotoalbum mit UV-Druck",
    "MILK Medium Premium Photo Album with UV Print": "Mittelgroßes Premium-Fotoalbum mit UV-Druck",
    "MILK Large Premium Leather Photo Album": "Großes Premium-Leder-Fotoalbum",
    "MILK Medium Premium Leather Photo Album": "Mittelgroßes Premium-Leder-Fotoalbum",
    "MILK Large Premium Leather Photo Album with UV Prin": "Großes Premium-Leder-Fotoalbum mit UV-Druck",
    "MILK Medium Premium Leather Photo Album with UV Print": "Mittelgroßes Premium-Leder-Fotoalbum mit UV-Druck",
    "Classic Photo Books": "Klassische Fotobücher",
    "MILK Classic Albums": "MILK Klassische Alben",
    "MILK Premium Medium Photo Books": "MILK Mittelgroße Premium-Fotobücher",
    "Moleskine Photo Books": "Moleskine-Fotobücher",
    "Moleskine Classic Photo Books": "Klassische Moleskine-Fotobücher",
    "Moleskine Monograph Photo Book": "Moleskine-Monographie",
    "MILK Premium Photo Book": "MILK Premium-Fotobuch",
    "MILK Premium Large Square Photo Book": "MILK Großes Quadratisches Premium-Fotobuch",
    "Classic 3 Piece Photo Book Set": "Klassisches 3-teiliges Fotobuch-Set",
    "Premium 3 Piece Photo Book Set": "Premium 3-teiliges Fotobuch-Set",
    "Premium 3 Piece Wedding Album Set": "Premium 3-teiliges Hochzeitsalbum-Set",
    "Classic 3 Piece Family Set": "Klassisches 3-teiliges Familien-Set",
    "Premium 3 Piece Family Set": "Premium 3-teiliges Familien-Set",
    "Classic 3 Piece Wedding Album Set": "Klassisches 3-teiliges Hochzeitsalbum-Set",
    "Classic 3 Piece Baby Set": "Klassisches 3-teiliges Baby-Set",
    "Large Premium Wedding Album": "Großes Premium-Hochzeitsalbum",
    "Large Premium Leather Wedding Album": "Großes Premium-Hochzeitsalbum aus Leder",
    "Medium Premium Albums": "Mittelgroße Premium-Alben",
    "Medium Premium Leather Albums": "Mittelgroße Premium-Lederalben",
    "Soft Cover Photo Books": "Softcover-Fotobücher",
    "Wedding Magazines": "Hochzeitsmagazine",
    "Medium Landscape Photo Album - Original": "Mittleres Fotoalbum im Querformat - Original",
    "Large Landscape Photo Album - Original": "Großes Fotoalbum im Querformat - Original",
    "Small Landscape Photo Book - Original": "Kleines Fotobuch im Querformat - Original",
    "Medium Landscape Photo Book - Original": "Mittelgroßes Fotobuch im Querformat - Original",
    "Large Landscape Photo Book - Original": "Großes Fotobuch im Querformat - Original",
    "Large Portrait Magazine": "Großes Magazin im Hochformat"
  },
  "es-ES": {
    "Classic Photo Books": "Fotolibros clásicos",
    "MILK Classic Albums": "Álbumes clásicos MILK",
    "MILK Premium Medium Photo Books": "Fotolibros medianos premium MILK",
    "Moleskine Photo Books": "Fotolibros Moleskine",
    "Moleskine Classic Photo Books": "Fotolibros Moleskine clásicos",
    "Moleskine Monograph Photo Book": "Fotolibros Moleskine monográficos",
    "MILK Premium Photo Book": "Fotolibros Premium MILK",
    "MILK Premium Large Square Photo Book": "Fotolibro cuadrado grande Premium MILK",
    "Classic 3 Piece Photo Book Set": "Kit clásico de fotolibros de 3 unidades",
    "Premium 3 Piece Photo Book Set": "Kit de fotolibros premium de 3 unidades",
    "Premium 3 Piece Wedding Album Set": "Kit de álbumes de boda premium de 3 unidades",
    "Classic 3 Piece Family Set": "Kit clásico de familia de 3 unidades",
    "Premium 3 Piece Family Set": "Kit premium de familia de 3 unidades",
    "Classic 3 Piece Wedding Album Set": "Kit clásico de álbumes de boda de 3 unidades",
    "Classic 3 Piece Baby Set": "Kit clásico de bebe de 3 unidades",
    "Large Premium Wedding Album": "Álbum de boda premium grande",
    "Large Premium Leather Wedding Album": "Álbum de boda premium grande de cuero",
    "Medium Premium Albums": "Álbumes medianos premium",
    "Medium Premium Leather Albums": "Álbum premium de cuero mediano",
    "Soft Cover Photo Books": "Fotolibros de tapa blanda",
    "Wedding Magazines": "Revistas de bodas",
    "Medium Landscape Photo Album - Original": "Álbum de fotos apaisado mediano - Original",
    "Large Landscape Photo Album - Original": "Álbum de fotos apaisado grande - Original",
    "Small Landscape Photo Book - Original": "Fotolibro apaisado pequeño - Original",
    "Medium Landscape Photo Book - Original": "Fotolibro apaisado mediano - Original",
    "Large Landscape Photo Book - Original": "Fotolibro apaisado grande - Original",
    "Large Portrait Magazine": "Revista de retrato grande",
    "MILK Medium Premium Photo Book": "Fotolibros premium medianos",
    "MILK Large Landscape/Portrait Premium Photo Book": "Fotolibros premium apaisados/retratos grandes",
    "MILK Large Square Premium Photo Book": "Fotolibros premium cuadrados grandes",
    "Premium Photo Books": "Fotolibros premium",
    "Classic Photo Albums": "Álbumes de fotos clásicos",
    "Premium Photo Albums": "Álbumes de fotos premium",
    "MILK Premium Photo Books": "Fotolibros premium",
    "MILK Premium Photo Albums": "Álbumes de fotos premium",
    "Large Premium Photo Album": "Álbumes de fotos premium grandes",
    "MILK Medium Premium Photo Album": "Álbumes de fotos premium medianos",
    "MILK Luxe Softcover Photo Book": "Fotolibros de tapa blanda",
    "Wedding Magazine": "Revistas de boda",
    "Medium Landscape Photo Book": "Fotolibro premium apaisado mediano",
    "Medium Square Photo Book": "Fotolibro premium cuadrado mediano",
    "Medium Portrait Photo Book": "Fotolibro premium de retrato mediano",
    "Large Landscape Photo Book": "Fotolibro premium apaisado grande",
    "Large Square Photo Book": "Fotolibro premium cuadrado grande",
    "Large Portrait Photo Book": "Fotolibro premium de retrato grande",
    "Medium Landscape Photo Album": "Álbum de fotos premium apaisado mediano",
    "Medium Square Photo Album": "Álbum de fotos premium cuadrado mediano",
    "Medium Portrait Photo Album": "Álbum de fotos premium de retrato mediano",
    "Large Landscape Photo Album": "Álbum de fotos premium apaisado grande",
    "Large Square Photo Album": "Álbum de fotos premium cuadrado grande",
    "Large Portrait Photo Album": "Álbum de fotos premium de retrato grande",
    "Small Landscape Photo Book - O": "Fotolibro clásico apaisado pequeño",
    "Medium Landscape Photo Book - O": "Fotolibro clásico apaisado mediano",
    "Large Landscape Photo Book - O": "Fotolibro clásico apaisado grande",
    "Medium Landscape Photo Album - O": "Álbum de fotos clásico apaisado mediano",
    "Large Landscape Photo Album - O": "Álbum de fotos clásico apaisado grande",
    "MSK Medium Landscape": "Fotolibro Moleskine apaisado mediano",
    "MSK Medium Square": "Fotolibro Moleskine cuadrado mediano",
    "MSK Landscape Monograph": "Monografía Moleskine apaisada",
    "MSK Classic Landscape": "Fotolibro Moleskine apaisado clásico",
    "MSK Classic Portrait": "Fotolibro Moleskine de retrato clásico",
    "Medium Square Soft Cover Photo Book": "Fotolibro de tapa blanda cuadrado mediano",
    "Medium Landscape Soft Cover Photo Book": "Fotolibro de tapa blanda apaisado mediano",
    "Medium Portrait Soft Cover Photo Book": "Fotolibro de tapa blanda de retrato mediano",
    "MILK Medium Premium Photo Book with UV Print": "Fotolibro premium mediano con impresión UV",
    "MILK Large Landscape/Portrait Premium Photo Book with UV Print": "Fotolibro premium apaisado/retrato grande con impresión UV",
    "MILK Large Square Premium Photo Book with UV Print": "Fotolibro premium cuadrado grande con impresión UV",
    "Premium Photo Books with UV Print": "Fotolibro premium con impresión UV",
    "Premium Photo Albums with UV Print": "Álbum de fotos premium con impresión UV",
    "MILK Premium Photo Books with UV Print": "Fotolibros premium con impresión UV",
    "MILK Premium Photo Albums with UV Print": "Álbum de fotos premium con Impresión UV",
    "Large Premium Photo Album with UV Print": "Álbum de fotos premium grande con impresión UV",
    "MILK Medium Premium Photo Album with UV Print": "Álbum de fotos premium mediano con impresión UV",
    "MILK Large Premium Leather Photo Album": "Álbum de fotos de cuero premium grande",
    "MILK Medium Premium Leather Photo Album": "Álbum de fotos de cuero premium mediano",
    "MILK Large Premium Leather Photo Album with UV Prin": "Álbum de fotos de cuero premium grande con impresión UV",
    "MILK Medium Premium Leather Photo Album with UV Print": "Álbum de fotos de cuero premium mediano con impresión UV",
  },
  "it-IT": {
    "Classic Photo Books": "Fotolibri classici",
    "MILK Classic Albums": "Album classici MILK",
    "MILK Premium Medium Photo Books": "Fotolibri MILK Premium medi",
    "Moleskine Photo Books": "Fotolibri Moleskine",
    "Moleskine Classic Photo Books": "Fotolibri Moleskine classici",
    "Moleskine Monograph Photo Book": "Fotolibro Moleskine monografico",
    "MILK Premium Photo Book": "Fotolibro Premium MILK",
    "MILK Premium Large Square Photo Book": "Fotolibro Premium quadrato grande MILK",
    "Classic 3 Piece Photo Book Set": "Set fotolibro classico 3 pezzi",
    "Premium 3 Piece Photo Book Set": "Set fotolibro Premium 3 pezzi",
    "Premium 3 Piece Wedding Album Set": "Set di album di matrimonio Premium 3 pezzi",
    "Classic 3 Piece Family Set": "Set classico famiglia 3 pezzi",
    "Premium 3 Piece Family Set": "Set Premium famiglia 3 pezzi",
    "Classic 3 Piece Wedding Album Set": "Set di album di matrimonio classico 3 pezzi",
    "Classic 3 Piece Baby Set": "Set classico per bambini 3 pezzi",
    "Large Premium Wedding Album": "Album di nozze Premium grande",
    "Large Premium Leather Wedding Album": "Album di nozze Premium grande in pelle",
    "Medium Premium Albums": "Album Premium medio",
    "Medium Premium Leather Albums": "Album in pelle Premium medio",
    "Soft Cover Photo Books": "Fotolibri con copertina morbida",
    "Wedding Magazines": "Riviste di matrimonio",
    "Medium Landscape Photo Album - Original": "Album fotografico medio orizzontale - originale",
    "Large Landscape Photo Album - Original": "Album fotografico orizzontale grande - originale",
    "Small Landscape Photo Book - Original": "Fotolibro orizzontale piccolo - originale",
    "Medium Landscape Photo Book - Original": "Fotolibro orizzontale medio - originale",
    "Large Landscape Photo Book - Original": "Fotolibro orizzontale grande - originale",
    "Large Portrait Magazine": "Rivista di ritratto grande",
  },
  "fr-FR": {
    "MILK Premium Photo Books": "Livres Photo Premium",
    "MILK Premium Photo Albums": "Albums photo premium",
    "Classic Photo Books": "Livres Photo Classiques",
    "MILK Classic Albums": "Albums Photo Classiques",
    "MILK Premium Medium Photo Books": "Livres Photo Moyen Premium",
    "Moleskine Photo Books": "Livres Photo Moleskine",
    "Moleskine Classic Photo Books": "Livres Photo Moleskine Classiques",
    "Moleskine Monograph Photo Book": "Livres Photo Moleskine Monographes",
    "MILK Premium Photo Book": "Livres Photo Premium",
    "MILK Premium Large Square Photo Book": "Livres Photo Premium Carré Large",
    "Classic 3 Piece Photo Book Set": "Set de 3 Livres Photo Classiques",
    "Premium 3 Piece Photo Book Set": "Set de 3 Albums de Mariage Classiques",
    "Premium 3 Piece Wedding Album Set": "Set de 3 Albums de Mariage Premium",
    "Classic 3 Piece Family Set": "Set de 3 Livres de Photo de Famille Classiques",
    "Premium 3 Piece Family Set": "Set de 3 Livres de Photo de Famille Premium",
    "Classic 3 Piece Wedding Album Set": "Set de 3 Albums de Mariage Classiques",
    "Classic 3 Piece Baby Set": "Set de 3 Livres de Photo de Bébé Classiques",
    "Large Premium Wedding Album": "Album de Mariage Premium Large",
    "Large Premium Leather Wedding Album": "Album de Mariage Premium Large en Cuir",
    "Medium Premium Albums": "Albums Photos Premium Moyen",
    "Medium Premium Leather Albums": "Albums Photos Premium Moyen en Cuir",
    "Soft Cover Photo Books": "Livres Photo à Couverture Souple",
    "Wedding Magazines": "Magazine de Mariage",
    "Medium Landscape Photo Album - Original": "Album Photo Paysage Moyen Classique",
    "Large Landscape Photo Album - Original": "Album Photo Paysage Large Classique",
    "Small Landscape Photo Book - Original": "Livre Photo Paysage Petit Classique",
    "Medium Landscape Photo Book - Original": "Livre Photo Paysage Moyen Classique",
    "Large Landscape Photo Book - Original": "Livre Photo Paysage Large Classique",
    "Large Portrait Magazine": "Magazine de Mariage",
    "MILK Premium Large Photo Books": "Livres photo Large premium",
    "MILK Photo Books and Albums": "Livres et Albums photo",
    "Large format Photo Books and Albums": "Livres et Albums photo larges",
    "MILK Premium Presentation Boxes": "Coffrets de présentation premium",
    "MILK Classic Medium Landscape Photo Book": "Livre photo paysage moyen classique",
    "MILK Classic Large Landscape Photo Book": "Livre photo paysage large classique",
    "MILK Premium 160 page Large Photo Book": "Livre photo premium large de 160 pages",
    "MILK Classic Large Landscape Photo Book + Box": "Livre photo paysage large classique + coffret de présentation",
    "MILK Premium Large Landscape + Portrait Photo Book + Box": "Livre photo paysage + portrait large + coffret de présentation",
    "MILK Premium Medium Photo Book + Pres Box": "Livre photo premium moyen + coffret de présentation",
    "MILK Premium Medium Landscape": "Livres premium moyen format paysage",
    "MILK Photo Books + Albums": "Livres et Albums Photo",
    "MILK Photo Book + Pres Box": "Livres photo + coffret de présentation",
    "MILK Photo Books": "Livres photo",
    "MILK Classic Range": "Gamme Classique",
    "Premium Presentation Box": "Coffrets de présentation premium",
    "Classic Presentation Box": "Coffrets de présentation classiques",
    "MILK Photo Album": "Albums photo",
    "MKT - MILKA Albums + Box": "Albums photos premium + coffret de présentation",
    "MKT ALL MILK & Pages": "Tous les produits MILK",
    "All Photo Books + upgrades": "Tous les livres photo",
    "Premium Photo Books": "Livres photo premium",
    "Premium Photo Albums": "Albums photo premium",
    "Premium Leather Photo Albums": "Albums photo en cuir",
    "Large Photo Books Portrait and Landscape": "Livres photo larges portrait et paysage",
  }
}